FROM python:2.7-alpine
LABEL maintainer arjuna.rahman@dsclogistics.com
COPY requirements.txt /app
RUN pip install -r /app/requirements.txt
COPY . /app
WORKDIR /app
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["application.py"]